# Generated by Django 5.2.5 on 2025-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo_imagem', models.ImageField(upload_to='imagens/')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(blank=True, max_length=100, null=True)),
                ('arquivo_audio', models.FileField(upload_to='audios/')),
                ('duracao_segundos', models.PositiveIntegerField(default=0, help_text='Duração do áudio em segundos.')),
                ('mood', models.CharField(blank=True, help_text='Ex: suspense, feliz, épico, etc.', max_length=50, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo_video', models.FileField(upload_to='videos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('duracao_segundos', models.PositiveIntegerField(default=0, help_text='Duração do vídeo em segundos.')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
    ]
